/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposOwnerRepoRouteImport } from './routes/repos/$owner/$repo'
import { Route as ReposOwnerRepoPullsNumRouteImport } from './routes/repos/$owner/$repo/pulls/$num'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerRepoRoute = ReposOwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => ReposRoute,
} as any)
const ReposOwnerRepoPullsNumRoute = ReposOwnerRepoPullsNumRouteImport.update({
  id: '/pulls/$num',
  path: '/pulls/$num',
  getParentRoute: () => ReposOwnerRepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/notifications': typeof NotificationsRoute
  '/repos': typeof ReposRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRouteWithChildren
  '/repos/$owner/$repo/pulls/$num': typeof ReposOwnerRepoPullsNumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/notifications': typeof NotificationsRoute
  '/repos': typeof ReposRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRouteWithChildren
  '/repos/$owner/$repo/pulls/$num': typeof ReposOwnerRepoPullsNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/notifications': typeof NotificationsRoute
  '/repos': typeof ReposRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRouteWithChildren
  '/repos/$owner/$repo/pulls/$num': typeof ReposOwnerRepoPullsNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/notifications'
    | '/repos'
    | '/search'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/repos/$owner/$repo'
    | '/repos/$owner/$repo/pulls/$num'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/notifications'
    | '/repos'
    | '/search'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/repos/$owner/$repo'
    | '/repos/$owner/$repo/pulls/$num'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/notifications'
    | '/repos'
    | '/search'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/repos/$owner/$repo'
    | '/repos/$owner/$repo/pulls/$num'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FilesRoute: typeof FilesRoute
  JobsRoute: typeof JobsRoute
  MemoryRoute: typeof MemoryRoute
  NotificationsRoute: typeof NotificationsRoute
  ReposRoute: typeof ReposRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  TerminalRoute: typeof TerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$repo': {
      id: '/repos/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/repos/$owner/$repo'
      preLoaderRoute: typeof ReposOwnerRepoRouteImport
      parentRoute: typeof ReposRoute
    }
    '/repos/$owner/$repo/pulls/$num': {
      id: '/repos/$owner/$repo/pulls/$num'
      path: '/pulls/$num'
      fullPath: '/repos/$owner/$repo/pulls/$num'
      preLoaderRoute: typeof ReposOwnerRepoPullsNumRouteImport
      parentRoute: typeof ReposOwnerRepoRoute
    }
  }
}

interface ReposOwnerRepoRouteChildren {
  ReposOwnerRepoPullsNumRoute: typeof ReposOwnerRepoPullsNumRoute
}

const ReposOwnerRepoRouteChildren: ReposOwnerRepoRouteChildren = {
  ReposOwnerRepoPullsNumRoute: ReposOwnerRepoPullsNumRoute,
}

const ReposOwnerRepoRouteWithChildren = ReposOwnerRepoRoute._addFileChildren(
  ReposOwnerRepoRouteChildren,
)

interface ReposRouteChildren {
  ReposOwnerRepoRoute: typeof ReposOwnerRepoRouteWithChildren
}

const ReposRouteChildren: ReposRouteChildren = {
  ReposOwnerRepoRoute: ReposOwnerRepoRouteWithChildren,
}

const ReposRouteWithChildren = ReposRoute._addFileChildren(ReposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FilesRoute: FilesRoute,
  JobsRoute: JobsRoute,
  MemoryRoute: MemoryRoute,
  NotificationsRoute: NotificationsRoute,
  ReposRoute: ReposRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  TerminalRoute: TerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
